# Generated by Django 5.2.13 on 2026-04-10 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Caixa')),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Busca')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Caixa de Email',
                'verbose_name_plural': 'Caixas de Email',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='ID único do email (para evitar duplicidade)', max_length=255, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('sender', models.EmailField(max_length=254)),
                ('received_at', models.DateTimeField(verbose_name='Recebido em (Timestamp IMAP)')),
                ('body_text', models.TextField(verbose_name='Corpo do Email (Texto Limpo)')),
                ('is_dispatched', models.BooleanField(default=False, verbose_name='Despachado para o Orquestrador?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.mailbox')),
            ],
            options={
                'verbose_name': 'Mensagem de Email',
                'verbose_name_plural': 'Mensagens de Email',
                'indexes': [models.Index(fields=['is_dispatched', 'received_at'], name='emails_emai_is_disp_e7ecd3_idx')],
            },
        ),
    ]
