# Generated by Django 5.2.13 on 2026-04-10 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Plano')),
                ('tier', models.CharField(choices=[('FREE', 'Trial Gratuito'), ('START', 'Plano Start'), ('PRO', 'Plano Profissional'), ('ENTERPRISE', 'Plano Enterprise')], max_length=20, unique=True)),
                ('price_brl', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('max_users', models.IntegerField(default=1, verbose_name='Limite de Utilizadores')),
                ('max_ai_extractions', models.IntegerField(default=100, verbose_name='Extrações IA por Mês')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plano Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle_month', models.DateField(verbose_name='Mês de Faturação')),
                ('extractions_count', models.IntegerField(default=0, verbose_name='Contagem de Extrações')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'billing_cycle_month')},
            },
        ),
    ]
