# Generated by Django 5.2.13 on 2026-04-10 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Perfil')),
                ('ai_provider', models.CharField(choices=[('OPENAI', 'OpenAI (GPT-3.5/GPT-4)'), ('GEMINI', 'Google Gemini (1.5 Flash)'), ('GROQ', 'Llama 3 (via Groq)')], default='OPENAI', max_length=20, verbose_name='Motor de IA')),
                ('system_prompt_template', models.TextField(help_text='Instrução detalhada para a IA. Use {data_atual} para a data de hoje.', verbose_name='System Prompt Template')),
                ('pydantic_schema_name', models.CharField(help_text='Nome da classe do schema em extraction.schemas (Ex: ProcessoJuridicoSchema).', max_length=100, verbose_name='Nome do Schema Pydantic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Perfil de Extração (Prompt)',
                'verbose_name_plural': 'Perfis de Extração (Prompts)',
            },
        ),
    ]
