version: '3.8'

# Diz ao front-end para se ligar à rede do Traefik (que já existe no back-end)
networks:
  proxy_net:
    external: true

services:
  frontend:
    container_name: cadrius_frontend
    build: .
    # Força a usar o script correto do Vite e expor a porta para a rede
    command: npm run dev -- --host 0.0.0.0 --port 3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=https://api.cadrius.ia.br
    networks:
      - proxy_net
    # A Magia do Roteamento: Diz ao Traefik que este contentor é o app.cadrius.ia.br
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_net"
      - "traefik.http.routers.cadrius-front.rule=Host(`app.cadrius.ia.br`)"
      - "traefik.http.routers.cadrius-front.entrypoints=web"
      - "traefik.http.services.cadrius-front.loadbalancer.server.port=3000"