// Ações da trilha de auditoria em português (CAD-233). O código técnico continua no title, para o suporte.
const DOMAIN = {
    auth: 'Acesso', data: 'Dados', user: 'Usuário', team: 'Equipe', org: 'Escritório', document: 'Documento', automation: 'Automação',
    marketing: 'Marketing', billing: 'Assinatura', backoffice: 'Gestão Cadrius', ai: 'IA', assistant: 'Assistente', contact: 'Contato',
    draft: 'Minuta', publication: 'Publicação', research: 'Processo', finance: 'Finanças', crm: 'Carteira', portal: 'Portal do cliente',
    fiscal: 'Fiscal', support: 'Suporte', security: 'Segurança', memory: 'Memória da IA', brain: 'Perfil do escritório', device: 'Relógio',
    connection: 'Integração', signature: 'Assinatura digital', compliance: 'Conformidade', privacy: 'Privacidade', legal: 'Termos',
    forense: 'Agenda forense', staff: 'Equipe Cadrius', gcal: 'Google', whatsapp: 'WhatsApp',
};
const LABEL = {
    'auth.login.success': 'Entrada no sistema', 'auth.login.failed': 'Senha errada no login', 'auth.logout': 'Saída do sistema',
    'auth.password.changed': 'Senha trocada', 'auth.password.reset': 'Nova senha pelo e-mail', 'auth.mfa.enabled': 'Verificação em duas etapas ligada',
    'auth.mfa.failed': 'Código de verificação errado', 'auth.sso.login': 'Entrada com Google/Microsoft',
    'data.bulk_read': 'Consulta de listas', 'data.read': 'Consulta de registro', 'data.export': 'Exportação de dados', 'data.import': 'Importação de planilha',
    'user.updated': 'Perfil atualizado', 'user.created': 'Conta criada',
    'team.member_invited': 'Convite enviado', 'team.member_removed': 'Pessoa removida da equipe', 'team.access_assigned': 'Acesso alterado',
    'document.extracted': 'Documento lido pela IA', 'document.extraction_confirmed': 'Leitura do documento confirmada',
    'automation.rule_created': 'Regra criada', 'automation.rule_updated': 'Regra alterada', 'automation.rule_deleted': 'Regra excluída',
    'automation.rule_enabled': 'Regra ligada', 'automation.rule_disabled': 'Regra desligada', 'automation.run_approved': 'Envio aprovado',
    'automation.run_rejected': 'Envio recusado',
    'marketing.content_created': 'Conteúdo criado', 'marketing.content_updated': 'Conteúdo alterado', 'marketing.content_published': 'Conteúdo publicado',
    'marketing.image_generated': 'Imagem do post gerada', 'marketing.video_requested': 'Vídeo pedido', 'marketing.asset_uploaded': 'Foto enviada',
    'draft.created': 'Minuta criada', 'draft.updated': 'Minuta alterada', 'draft.exported': 'Minuta exportada', 'draft.template_saved': 'Modelo de minuta salvo',
    'publication.captured': 'Publicação capturada', 'publication.reviewed': 'Publicação revisada',
    'contact.created': 'Contato criado', 'contact.updated': 'Contato alterado', 'contact.deleted': 'Contato excluído',
    'ai.request': 'Pedido à IA', 'ai.blocked': 'Pedido à IA bloqueado', 'assistant.action': 'Ação do Assistente',
    'billing.checkout': 'Pagamento iniciado', 'billing.payment_confirmed': 'Pagamento confirmado', 'billing.payment_failed': 'Falha no pagamento',
    'brain.profile_updated': 'Perfil do escritório alterado', 'connection.tested': 'Integração testada',
    'admin.access': 'Acesso ao painel técnico', 'admin.add': 'Registro criado no painel técnico',
    'admin.change': 'Registro alterado no painel técnico', 'admin.delete': 'Registro excluído no painel técnico',
    'admin.login': 'Entrada no painel técnico', 'ai.autonomy_changed': 'Autonomia da IA alterada',
    'ai.draft_created': 'Rascunho criado pela IA', 'ai.route_changed': 'Rota de IA alterada',
    'ai.rule_decided': 'Regra aprendida decidida', 'anomaly.detected': 'Comportamento incomum detectado',
    'anomaly.reviewed': 'Alerta revisado', 'anonymization.run': 'Dados anonimizados',
    'assistant.key_removed': 'Chave de IA removida', 'assistant.key_saved': 'Chave de IA salva',
    'assistant.mcp_call': 'Pedido pelo conector (Claude/ChatGPT)', 'assistant.token_created': 'Conector ligado',
    'assistant.token_revoked': 'Conector desligado', 'audit.chain_broken': 'Trilha de auditoria com falha',
    'audit.chain_verified': 'Trilha de auditoria verificada', 'audit.export': 'Auditoria exportada',
    'audit.viewed': 'Auditoria consultada', 'auth.login.failure': 'Senha errada no login',
    'auth.login.locked': 'Login bloqueado por tentativas', 'auth.mfa.disabled': 'Verificação em duas etapas desligada',
    'auth.mfa.recovery_regenerated': 'Códigos de recuperação refeitos', 'auth.mfa.reset': 'Verificação em duas etapas redefinida',
    'auth.password.change': 'Senha trocada', 'auth.password.forced_change': 'Troca obrigatória de senha',
    'auth.password.reset_requested': 'Pedido de nova senha', 'auth.password.temp_set': 'Senha temporária definida',
    'auth.register': 'Cadastro feito', 'auth.token.refresh': 'Sessão renovada',
    'automation.discovery': 'Sugestões de automação geradas', 'automation.shortcut_fired': 'Atalho acionado',
    'automation.shortcut_rotated': 'Atalho renovado', 'automation.suggestion_decided': 'Sugestão da IA decidida',
    'backoffice.action': 'Ação da Gestão Cadrius', 'billing.admin_changed': 'Ajuste financeiro da Gestão',
    'billing.charge_created': 'Cobrança criada', 'billing.coupon_applied': 'Cupom aplicado',
    'billing.coupon_saved': 'Cupom salvo', 'billing.credits_purchased': 'Créditos comprados',
    'billing.price_changed': 'Preço alterado', 'billing.subscription_canceled': 'Assinatura cancelada',
    'compliance.assessment_updated': 'Avaliação de conformidade alterada', 'connection.created': 'Integração conectada',
    'connection.deleted': 'Integração removida', 'connection.updated': 'Integração alterada',
    'consent.granted': 'Termo aceito', 'consent.revoked': 'Consentimento retirado',
    'contact.cnpj_lookup': 'Consulta de CNPJ', 'crm.agreement_canceled': 'Contrato de honorários cancelado',
    'crm.agreement_created': 'Contrato de honorários criado', 'crm.opportunity_saved': 'Oportunidade salva',
    'crm.stage_changed': 'Oportunidade mudou de etapa', 'crm.success_registered': 'Êxito registrado',
    'data.download': 'Arquivo baixado', 'device.command': 'Comando pelo relógio',
    'device.created': 'Aparelho adicionado', 'device.decision': 'Decisão pelo relógio',
    'device.revoked': 'Aparelho removido', 'document.blocked': 'Documento bloqueado pela política',
    'draft.deleted': 'Minuta excluída', 'dsr.fulfilled': 'Pedido de titular atendido',
    'dsr.opened': 'Pedido de titular aberto', 'dsr.rejected': 'Pedido de titular recusado',
    'extractionprofile.created': 'Perfil de leitura criado', 'extractionprofile.deleted': 'Perfil de leitura excluído',
    'extractionprofile.updated': 'Perfil de leitura alterado', 'finance.expense_created': 'Despesa lançada',
    'finance.expense_deleted': 'Despesa excluída', 'finance.receivable_paid': 'Recebimento confirmado',
    'finance.receivable_reopened': 'Cobrança reaberta', 'finance.receivable_saved': 'Valor a receber salvo',
    'finance.recurring_deleted': 'Despesa fixa excluída', 'finance.recurring_saved': 'Despesa fixa salva',
    'finance.settings_saved': 'Configuração financeira salva', 'finance.webhook_configured': 'Aviso de pagamento configurado',
    'fiscal.nfse_canceled': 'NFS-e cancelada', 'fiscal.nfse_requested': 'NFS-e pedida',
    'fiscal.obligation_done': 'Obrigação fiscal cumprida', 'fiscal.office_nfse_requested': 'NFS-e do escritório pedida',
    'forense.suspension_deleted': 'Suspensão de prazo excluída', 'forense.suspension_saved': 'Suspensão de prazo salva',
    'integration.call': 'Chamada de integração', 'mailbox.created': 'Caixa de e-mail conectada',
    'mailbox.deleted': 'Caixa de e-mail removida', 'mailbox.updated': 'Caixa de e-mail alterada',
    'marketing.asset_deleted': 'Foto excluída', 'marketing.campaign_saved': 'Campanha salva',
    'marketing.content_deleted': 'Conteúdo excluído', 'marketing.form_saved': 'Formulário de captação salvo',
    'marketing.lead_captured': 'Contato captado', 'marketing.survey_answered': 'Pesquisa respondida',
    'member.invited': 'Pessoa convidada', 'member.removed': 'Pessoa removida',
    'member.role_changed': 'Cargo alterado', 'memory.added': 'Memória da IA adicionada',
    'memory.deleted': 'Memória da IA excluída', 'message.sent': 'Mensagem enviada',
    'org.closure': 'Encerramento do escritório', 'org.updated': 'Dados do escritório alterados',
    'permission.denied': 'Acesso negado', 'portal.link_created': 'Link do portal criado',
    'portal.link_revoked': 'Link do portal revogado', 'portal.viewed': 'Portal visto pelo cliente',
    'publication.watch_added': 'OAB adicionada', 'publication.watch_removed': 'OAB removida',
    'ratelimit.hit': 'Excesso de pedidos', 'research.case_added': 'Processo acompanhado',
    'research.case_removed': 'Processo deixou de ser acompanhado', 'research.movements_found': 'Andamentos novos',
    'retention.purged': 'Dados antigos apagados', 'security.ip_blocked': 'IP bloqueado',
    'security.ip_unblocked': 'IP desbloqueado', 'signature.requested': 'Assinatura pedida',
    'staff.areas_changed': 'Áreas da equipe Cadrius alteradas', 'support.access_granted': 'Acesso do suporte liberado',
    'support.access_revoked': 'Acesso do suporte retirado', 'support.customization_requested': 'Parametrização pedida',
    'support.customization_updated': 'Parametrização atualizada', 'support.staff_reply': 'Resposta do suporte',
    'support.ticket_opened': 'Chamado aberto', 'team.access_group_deleted': 'Grupo de acesso excluído',
    'team.access_group_saved': 'Grupo de acesso salvo', 'webhook.accepted': 'Aviso externo recebido',
    'webhook.invalid_token': 'Aviso externo recusado', 'workflow.activated': 'Fluxo ligado',
    'workflow.approved': 'Fluxo aprovado', 'workflow.created': 'Fluxo criado',
    'workflow.deleted': 'Fluxo excluído', 'workflow.updated': 'Fluxo alterado',
};

export function auditLabel(action) {
    if (!action) return '—';
    if (LABEL[action]) return LABEL[action];
    const [domain, ...rest] = String(action).split('.');
    const what = rest.join(' ').replace(/_/g, ' ');
    return `${DOMAIN[domain] || domain}${what ? `: ${what}` : ''}`;
}
