# Generated by Django 5.2.13 on 2026-04-10 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload_mapping', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='integrations.appconnection')),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('WEBHOOK', 'Webhook Externo (Genérico)'), ('WHATSAPP_EVOLUTION', 'Enviar WhatsApp (Evolution API)'), ('EMAIL_SMTP', 'Enviar E-mail (Nativo)')], default='WEBHOOK', max_length=50)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('payload_template', models.TextField(help_text='Template JSON com variáveis {{chave}}')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('FAILED', 'Falha'), ('PENDING_REVIEW', 'Aguardando Revisão Humana')], max_length=20)),
                ('trigger_payload', models.JSONField(blank=True, null=True)),
                ('final_result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, help_text='Tempo de execução em milissegundos para cálculo de ROI', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'status'], name='workflows_e_workflo_2441db_idx'), models.Index(fields=['created_at'], name='workflows_e_created_bfed85_idx')],
            },
        ),
    ]
