# Generated by Django 6.0.4 on 2026-05-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='webhook_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
