# Generated by Django 5.2.14 on 2026-05-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_trigger_webhook_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha'), ('PENDING_REVIEW', 'Aguardando Revisão Humana')], max_length=20),
        ),
    ]
