# Generated by Django 5.2.13 on 2026-04-10 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='billing.subscriptionplan', verbose_name='Plano Atual'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organization')},
        ),
    ]
