# Generated by Django 5.2.13 on 2026-04-10 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Conexão (ex: WhatsApp do Suporte)')),
                ('app_name', models.CharField(choices=[('WHATSAPP', 'WhatsApp (API Meta/Evolution)'), ('SHEETS', 'Google Sheets'), ('CLICKUP', 'ClickUp'), ('TRELLO', 'Trello'), ('TELEGRAM', 'Telegram'), ('ASTREA', 'Astrea (Sistema Jurídico)'), ('WEBHOOK', 'Webhook Customizado')], max_length=50, verbose_name='Aplicativo')),
                ('credentials', models.JSONField(default=dict, help_text='Credenciais no formato JSON. (Deverão ser encriptadas no banco!)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Conexão de App',
                'verbose_name_plural': 'Conexões de Apps',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('FAILED', 'Falha na Integração'), ('PENDING', 'Pendente de Execução'), ('RETRIED', 'Tentativa de Retry')], default='PENDING', max_length=20)),
                ('request_data', models.JSONField(blank=True, help_text='Payload enviado ao serviço externo.', null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, help_text='Resposta recebida do serviço externo.', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integrations.appconnection')),
            ],
            options={
                'verbose_name': 'Log de Integração',
                'verbose_name_plural': 'Logs de Integração',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['connection', 'status'], name='integration_connect_d59868_idx')],
            },
        ),
    ]
