name: CI/CD Pipeline Cadrius Front-end

on:
  push:
    branches: [ main ]

jobs:
  test-frontend:
    name: Testes e Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint 

  deploy:
    name: Deploy para a Locaweb
    needs: [test-frontend] 
    runs-on: ubuntu-latest
    steps:
      - name: Executando Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LOCAWEB_HOST }}
          username: ${{ secrets.LOCAWEB_USER }}
          key: ${{ secrets.LOCAWEB_SSH_KEY }}
          script: |
            # Entra na pasta do Front-end no servidor 
            cd /opt/cadrius/Cadrius---Front-end
            git stash
            git pull origin main
            echo "VITE_API_URL=https://api.cadrius.ia.br" > .env
            sudo docker compose up -d --build